#!/usr/bin/env bash
#it configures a brand new Ubuntu machine to the requirements asked in this task

sudo apt-get update
sudo apt-get install -y nginx

sudo sh -c 'echo "Hello World!" > /usr/share/nginx/html/index.html'

sudo sed -i '/listen 80 default_server;/a \\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

sudo sed -i "s/server_name _;/$new_string/" /etc/nginx/sites-enabled/default

echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/custom_404.html > /dev/null

sudo sed -i "/server_name _/a add_header X-served-By $HOSTNAME;" /etc/nginx/sites-enabled/default

sudo nginx -t

sudo service nginx restart
