#!/usr/bin/env bash
#Install and configure HAproxy on your lb-01 server

sudo apt-get update

sudo apt-get -y install software-properties-common

sudo add-apt-repository -y ppa:vbernat/haproxy-2.0
sudo apt-get update
sudo apt-get -y install haproxy=2.0.\*
options="\n\tbind :80\n\tmode http\n\tuse_backend mybackend\nbackend mybackend\n\tbalance roundrobin\n\tserver 386926-web-01 52.87.3.107:80 check\n\tserver 386926-web-02 52.87.219.206:80 check"
sed -i '/errorfile 504/a frontend myconf' /etc/haproxy/haproxy.cfg
sed -i "s/frontend myconf/&$options/g" /etc/haproxy/haproxy.cfg
sudo service haproxy restart
