#!/usr/bin/env bash
#Bash script that configures a server

sudo apt-get update
sudo apt-get install -y nginx net-tools

sudo service nginx start

sudo nginx -t

sudo sed -i '/listen/s/#* *listen *80/listen 80/' /etc/nginx/nginx.conf

sudo service nginx restart
