#!/usr/bin/env bash
#displays all active IPv4 IPs on the machine it’s executed on

interfaces=$(ip -o link show | awk -F': ' '{print $2}')

# Display IPv4 addresses for each interface
for interface in $interfaces; do
    ipv4=$(ip -o -4 addr show dev $interface | awk '{split($4, a, "/"); print a[1]}')
    if [ -n "$ipv4" ]; then
        echo "$ipv4"
    fi
done | sort -k4,4n
