#!/usr/bin/env bash

# Use the absolute path to the private key file
private_key="~/.ssh/school"

# Set the server address
server_address="ubuntu@34.239.254.85"

# SSH connection command
ssh -i "$private_key" "$server_address"
